### ISSUE TITLE
Strange results running the benchmark (on inferno)

### ISSUE THREAD

**Issue by joakin** [taobaofed/rx-ssr-compare#16]
Hi,

I run the benchmark from master and for some reason inferno is coming up with results two orders of magnitude faster:

```
server-side-rendering-comparison (master=) $ NODE_ENV=production node benchmarks/renderToString.js
React#renderToString x 162 ops/sec ±4.07% (64 runs sampled)
Rax#renderToString x 239 ops/sec ±5.45% (67 runs sampled)
Inferno#renderToString x 67,423 ops/sec ±4.18% (73 runs sampled)
Preact#renderToString x 840 ops/sec ±3.86% (74 runs sampled)
Rapscallion#render x 1,315 ops/sec ±3.65% (71 runs sampled)
Marko#renderToString x 5,145 ops/sec ±3.22% (76 runs sampled)
Xtpl#renderFile x 6,146 ops/sec ±7.36% (61 runs sampled)
Fastest is Inferno#renderToString

server-side-rendering-comparison (master=) $ NODE_ENV=production node benchmarks/renderToString.js
React#renderToString x 182 ops/sec ±1.85% (72 runs sampled)
Rax#renderToString x 261 ops/sec ±4.46% (70 runs sampled)
Inferno#renderToString x 73,376 ops/sec ±11.25% (78 runs sampled)
Preact#renderToString x 920 ops/sec ±1.17% (81 runs sampled)
Rapscallion#render x 1,476 ops/sec ±2.28% (76 runs sampled)
Marko#renderToString x 5,756 ops/sec ±2.04% (81 runs sampled)
Xtpl#renderFile x 6,375 ops/sec ±6.35% (60 runs sampled)
Fastest is Inferno#renderToString
```

How can this be? 70.000 vs 100s or 1000s? I've looked at the code but can't see anything weird.

Is the inferno benchmark broken? Can somebody reproduce?

---
System info:
* OSX 10.11.5 (15F34)
* node v7.9.0
* npm v4.6.1

**Comment by joakin** [comment]
Inferno wasn't actually rendering the big trees because of some transpilation problem so that is why it was that fast.

I've fixed the build process in #18, and then it returns more believable results:

```
server-side-rendering-comparison (fix-inferno $) $ NODE_ENV=production node benchmarks/renderToString.js
React#renderToString x 161 ops/sec ±2.21% (64 runs sampled)
Rax#renderToString x 248 ops/sec ±4.87% (63 runs sampled)
Inferno#renderToString x 683 ops/sec ±2.36% (83 runs sampled)
Preact#renderToString x 750 ops/sec ±3.59% (75 runs sampled)
Rapscallion#render x 1,425 ops/sec ±3.04% (76 runs sampled)
Marko#renderToString x 5,730 ops/sec ±1.49% (81 runs sampled)
Xtpl#renderFile x 6,655 ops/sec ±6.12% (61 runs sampled)
Fastest is Xtpl#renderFile
```

**Comment by ThePatriotic** [comment]
I applied this patch and still see wrong inferno results:

NODE_ENV=production node benchmarks/renderToString.js

React#renderToString x 158 ops/sec ±5.35% (66 runs sampled)
Rax#renderToString x 361 ops/sec ±4.36% (69 runs sampled)
Inferno#renderToString x 219,012 ops/sec ±2.28% (84 runs sampled)
Preact#renderToString x 1,291 ops/sec ±2.52% (80 runs sampled)
Rapscallion#render x 243 ops/sec ±36.76% (80 runs sampled)
Marko#renderToString x 7,597 ops/sec ±3.70% (81 runs sampled)
Xtpl#renderFile x 6,494 ops/sec ±5.85% (53 runs sampled)
Fastest is Inferno#renderToString

**Comment by wssgcg1213** [comment]
It seems fixed in latest version
